### PR TITLE
refactor `convertToData()`

### PR DESCRIPTION
**Pull request by stlaz**
This PR simplifies the way the code in `convertToData()` works

### CODE REVIEW

**Comment by enj** [comment]
/hold

@stlaz said he would manually test this before trying to merge.

**Comment by stlaz** [comment]
@enj this still seems to work, the `OAuth` config
```
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: OAuth
  metadata:
    creationTimestamp: 2019-01-17T08:37:00Z
    generation: 7
    name: cluster
    namespace: ""
    resourceVersion: "1443579"
    selfLink: /apis/config.openshift.io/v1/oauths/cluster
    uid: 0e8fddf8-1a33-11e9-9236-664f163f5f0f
  spec:
    identityProviders:
    - challenge: true
      htpasswd:
        fileData:
          name: tehhtpasswd
      login: true
      mappingMethod: claim
      name: awesomeness
      type: HTPasswd
    tokenConfig:
      accessTokenMaxAgeSeconds: 86400
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

properly generates:
```
...
    "identityProviders": [
      {
        "challenge": true,
        "login": true,
        "mappingMethod": "claim",
        "name": "awesomeness",
        "provider": {
          "apiVersion": "osin.config.openshift.io/v1",
          "file": "/var/config/user/idp/0/secret/v4-0-config-user-idp-0-tehhtpasswd-htpasswd/htpasswd",
          "kind": "HTPasswdPasswordIdentityProvider"
        }
      }
    ],
...
```
and the secret `openshift-osin v4-0-config-user-idp-0-tehhtpasswd-htpasswd` is synced in `openshift-osin` NS.

**Comment by stlaz** [comment]
I'll have a follow-up to this expanding the `idpSyncData` struct by methods that add the `sourceData` structs, which should make it then easy to merge it with the func that converts idps to osinv1.
I'll do both of that in the one follow-up PR. That should get us to the point where we can start caring about the errors bubbling to the operator status.

**Comment by stlaz** [comment]
@ericavonb Thank you for your review. I moved the changes done here to a broader PR: https://github.com/openshift/cluster-osin-operator/pull/28 which superseeds this one.

Closing in the favour of the above PR.

**Pull request closed without merging**
